language: android
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.2
  - android-24

  - extra-android-support
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-google-google_play_services

  - sys-img-armeabi-v7a-android-24

before_script:
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  
